name: qlutter
description: Qlutter game project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: '3.7.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.17
  # shared_preferences_web: ^2.0.5
  flutter_animated_dialog: ^2.0.1
  url_launcher: ^6.1.8
  go_router: ^14.6.2  
  # audioplayers: ^3.0.1
  # games_services: ^3.0.0
  cupertino_icons: ^1.0.2

  logging: ^1.1.0
  provider: ^6.0.2

  # dio: ^5.0.1
  freezed: ^2.3.2  
  injectable: ^2.1.0  
  flutter_bloc: ^8.1.2
  get_it: ^8.0.3
  # pretty_dio_logger: ^1.1.1
  hydrated_bloc: ^9.1.0
  # hive: ^2.2.3
  path_provider: ^2.0.13
  # connectivity_plus: ^3.0.3

  # google_mobile_ads: ^2.0.1  # Ads
  # in_app_purchase: ^3.0.1  # In-app purchases
  # rive: ^0.13.20
  flutter_svg: ^2.0.3 
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  animated_theme_switcher: ^2.0.8
  freezed_annotation: ^2.2.0
  slang: ^4.4.0
  slang_flutter: ^4.4.0

  flutter_native_splash: ^2.3.1

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.4.0 

  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/qlutter.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/qlutter.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"

flutter:  
  uses-material-design: true

  fonts:
    - family: DS Goose
      fonts:
          - asset: assets/fonts/DS Goose.ttf
    # - family: Permanent Marker
    #   fonts:
    #       - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    # - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
    #         weight: 700
  assets:
    - assets/icon/
    - assets/rive/
    - assets/data/
    
# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/icon_foreground.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/qlutter.png
  web: false
 