name: qlutter
description: Qlutter game project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.2

environment:
  sdk: '3.7.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  flutter_animated_dialog: ^2.0.1
  url_launcher: ^6.3.1
  go_router: ^14.8.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  animated_theme_switcher: ^2.0.10  
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  flutter_native_splash: ^2.4.5

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.5.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/qlutter.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/qlutter.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"

flutter:  
  uses-material-design: true

  fonts:
    - family: DS Goose
      fonts:
          - asset: assets/fonts/DS Goose.ttf
    # - family: Permanent Marker
    #   fonts:
    #       - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    # - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
    #         weight: 700
  assets:
    - assets/icon/
    - assets/rive/
    - assets/data/
    
# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/icon_foreground.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/qlutter.png
  web: false
 