name: qlutter
description: Qlutter game project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_animated_dialog: ^2.0.1
  url_launcher: ^6.1.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

assets:
      - assets/icon/icon_foreground.png
      # - assets/icon/icon_round.png
      - assets/classic.txt

flutter_native_splash:
  color: "#121212"
  image: assets/icon/icon_foreground.png
  web: false
 