class LevelMaps {
  static const List<List<String>> levels = [
    [
      'B B B B B B B',
      'B LIT T T T RIT B',
      'B LID D D LOD R B',
      'B B B B L R B',
      'B B B B L R B',
      'B B B B LID RID B',
      'B B B B B B B',
    ],
    [
      'B B LIT RIT B B B',
      'B LIT LOT ROT T RIT B',
      'B L N N N ROT RIT',
      'B L N N N ROD RID',
      'B LID LOD N N R B',
      'B B LID D D RID B',
      'B B B B B B B',
    ],
    [
      'B B B B B B B B B B B',
      'B B B B B LIT T T RIT B',
      'B B B B LIT LOT N N R B',
      'B B B LIT LOT N N N ROT RIT ',
      'B B LIT LOT N N N N ROD RID',
      'B LIT LOT N N N N N R B',
      'B L N N N N N N R B',
      'B L N N N N N N R B',
      'B LID LOD ROD D LOD ROD D RID B',
      'B B LID RID B LID RID B B B',
    ],
    [
      "B B B B LIT RIT B B B B",
      "B LIT T T LOT ROT T RIT B B B",
      "B L N N N N N R B B",
      "B L N N N N N R B B",
      "LIT LOT N N N N N R B B",
      "LID LOD N N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N R B",
      "B L N ROD LOD N ROD D RID B",
      "B LID D RID LID D RID B B B",
      "B B B B B B B B B B",
    ],
    [
      "B B B B B LIT RIT B B B",
      "B B LIT T T LOT ROT RIT B B",
      "B LIT LOT N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N ROT RIT",
      "B L N N N N N N ROD RID",
      "B L N N N N N N R B",
      "B LID LOD N N N N ROD RID B",
      "B B LID D LOD ROD D RID B B",
      "B B B B LID RID B B B B",
    ],
    [
      //5
      "B B B B B B B B B B B",
      "B B B LIT T RIT B B B",
      "B B B L N R B B B",
      "B LIT T LOT N ROT T T RIT",
      "LIT LOT N N N N N ROD RID",
      "LID LOD N N N N N R B",
      "B L N N N N N R B",
      "LIT LOT N N N N N R B",
      "LID LOD N N N N N R B",
      "B LID D LOD N ROD D RID B",
      "B B B L N R B B B",
      "B B B LID D RID B B B",
      "B B B B B B B B B B B",
    ],
    // 6
    [
      "B B B LIT RIT B B B B",
      "B B B L ROT RIT B B B",
      "B B B L N R B B B",
      "LIT T T LOT N ROT T RIT B",
      "LID LOD N N N N N ROT RIT",
      "B LID D LOD N ROD D D RID",
      "B B B L N R B B B",
      "B B B LID LOD R B B B",
      "B B B B LID RID B B B",
      "B B B B B B B B B B",
    ], // 7
    [
      "B B B B B B LIT RIT B B B B B B",
      "B LIT T T T T LOT ROT T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID LOD N N ROD D LOD ROD D LOD N N R B",
      "B L N N R B LID RID B L N N R B",
      "B LID D D RID B B B B LID D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    [
      // 8
      "B B B B B B LIT RIT B B B B B",
      "B LIT T T T T LOT ROT T T T RIT B",
      "B L N N N 5 N N N N N R B",
      "LIT LOT N N N N N N N N ROD RID B",
      "LID LOD N N N N N N N N ROT RIT B",
      "B L N ROD LOD N N N 4 N N R B",
      "B L ROD LB LOT N N N N N N R B",
      "B L ROT LOT N N N N N N N ROT RIT",
      "B L N N N N 3 N N N N ROD RID",
      "B L N ROD LOD N N N N N N R B",
      "B L N ROT LOT N N N N N N R B",
      "B LID D D D LOD ROD D D D D RID B",
      "B B B B B LID RID B B B B B B",
      "B B B B B B B B B B B B B",
    ],
    // 9
    [
      "B B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N 44 R B",
      "B L N N N 6 N N N N N N R B",
      "B L N N N N N N N N N 44 R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N 44 R B",
      "B L N 2 N N N N N N N 5 R B",
      "B L N N N N N 6 N N N 44 R B",
      "B L N N N N N N N N 2 ROD RID B",
      "B L N N N N N N N N N ROT RIT B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B B",
    ],
    [
      // ten
      "B B B LIT RIT B B B B B B B B B B",
      "B LIT T LOT ROT T T T T T T RIT B B",
      "B L 2 N 6 N N N N N N ROT RIT B",
      "B L ROD LOD ROD LOD ROD LOD N N N N R B",
      "B L R L R L R L ROD LOD N N R B",
      "B L R L R L R L R L N N R B",
      "B L R L R L R L R L N N R B",
      "B L ROT LOT R L R L R L N N R B",
      "B L N N ROT LOT ROT LOT ROT LOT N N R B",
      "B L N N N N N 44 N N N N R B",
      "B L N 4 N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D LOD ROD D D RID B",
      "B B B B B B B B LID RID B B B B",
    ],
    [
      // ELEVEN
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N ROD D D D D LOD N N R B",
      "B L N ROD LB T T T RIT L N N R B",
      "B L N R L 44 44 44 R L N N R B",
      "B L N R L 44 44 44 R L N N R B",
      "B L N R L 44 44 ROD RID L N N R B",
      "B L N R LID D D RID B L N N R B",
      "B L N ROT T T T T T RB LOD N R B",
      "B L N N N N N N N ROT LOT N R B",
      "B L N N N N 5 3 N N N N R B",
      "B LID LOD ROD D D D D D D D D RID B",
      "B B LID RID B B B B B B B B B B",
    ],
    [],
    [],
  ];
}
