class LevelMaps {
  static const List<List<String>> levels = [
    [
      'B B B B B B B',
      'B LIT T T T RIT B',
      'B LID D D LOD R B',
      'B B B B L R B',
      'B B B B L R B',
      'B B B B LID RID B',
      'B B B B B B B',
    ],
    [
      'B B LIT RIT B B B',
      'B LIT LOT ROT T RIT B',
      'B L N N N ROT RIT',
      'B L N N N ROD RID',
      'B LID LOD N N R B',
      'B B LID D D RID B',
      'B B B B B B B',
    ],
    [
      'B B B B B LIT T T RIT B',
      'B B B B LIT LOT N N R B',
      'B B B LIT LOT N N N R B',
      'B B LIT LOT N N N N ROT RIT',
      'B LIT LOT N N N N N ROD RID',
      'B L N N N N N N R B',
      'B L N N N N N N R B',
      'B L N N N N N N R B',
      'B LID LOD ROD D LOD ROD D RID B',
      'B B LID RID B LID RID B B B',
    ],
    [
      "B B B B LIT RIT B B B B",
      "B LIT T T LOT ROT T RIT B B B",
      "B L N N N N N R B B",
      "B L N N N N N R B B",
      "LIT LOT N N N N N R B B",
      "LID LOD N N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N R B",
      "B L N ROD LOD N ROD D RID B",
      "B LID D RID LID D RID B B B",
      "B B B B B B B B B B",
    ],
    [
      "B B B B B LIT RIT B B B",
      "B B LIT T T LOT ROT RIT B B",
      "B LIT LOT N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N ROT RIT",
      "B L N N N N N N ROD RID",
      "B L N N N N N N R B",
      "B LID LOD N N N N ROD RID B",
      "B B LID D LOD ROD D RID B B",
      "B B B B LID RID B B B B",
    ],
    [
      "B B B B B B B B B B B",
      "B B B LIT T RIT B B B",
      "B B B L N R B B B",
      "B LIT T LOT N ROT T T RIT",
      // "B L N N N N N ROT RIT",
      "LIT LOT N N N N N ROD RID",
      "LID LOD N N N N N R B",
      "B L N N N N N R B",
      "LIT LOT N N N N N R B",
      "LID LOD N N N N N R B",
      "B LID D LOD N ROD D RID B",
      "B B B L N R B B B",
      "B B B LID D RID B B B",
      "B B B B B B B B B B B",
    ],
  ];
}
