name: ui
description: "Qlutter UI kit"
version: 0.0.2
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

